/* SPDX-License-Identifier: ISC
 *
 * Derived from the Nintendo 64 save-type database in the ares emulator
 * (mia/medium/nintendo-64.cpp). ares is ISC licensed and its notice is
 * retained here as that licence requires:
 *
 *   Copyright (c) 2004-2025 ares team, Near et al
 *
 *   Permission to use, copy, modify, and/or distribute this software for any
 *   purpose with or without fee is hereby granted, provided that the above
 *   copyright notice and this permission notice appear in all copies.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *   WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *   ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *   WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *   ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *   OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#include "rom_db.h"

/* GENERATED by tools/build_rom_db.py -- do not edit by hand.
   Source: https://raw.githubusercontent.com/ares-emulator/ares/master/mia/medium/nintendo-64.cpp (ISC) */

static const sm_rom_db_entry_t ROM_DB[SM_ROM_DB_COUNT] = {
    {{'C','D','Z'}, '\0', 255u, 4u, 2u}, /* Dezaemon 3D */
    {{'C','F','Z'}, '\0', 255u, 3u, 2u}, /* F-Zero X (J) */
    {{'C','L','B'}, '\0', 255u, 1u, 2u}, /* Mario Party (NTSC) */
    {{'C','P','2'}, '\0', 255u, 5u, 4u}, /* Pocket Monsters Stadium 2 (J) */
    {{'C','P','S'}, '\0', 255u, 3u, 4u}, /* Pocket Monsters Stadium (J) */
    {{'C','Z','L'}, '\0', 255u, 3u, 2u}, /* Legend of Zelda: Ocarina of Time [Zelda no Densetsu - Toki */
    {{'N','2','2'}, '\0', 255u, 0u, 3u}, /* Ready 2 Rumble Boxing - Round 2 */
    {{'N','2','M'}, '\0', 255u, 0u, 3u}, /* Madden Football 2002 */
    {{'N','2','P'}, '\0', 255u, 0u, 3u}, /* Rampage 2 - Universal Tour */
    {{'N','2','V'}, '\0', 255u, 0u, 3u}, /* Chameleon Twist 2 (U + E) */
    {{'N','3','2'}, '\0', 255u, 0u, 3u}, /* Army Men - Sarge's Heroes 2 */
    {{'N','3','D'}, '\0', 255u, 2u, 2u}, /* Doraemon 3: Nobita no Machi SOS! */
    {{'N','3','H'}, 'J', 255u, 3u, 2u}, /* special case */
    {{'N','3','H'}, '\0', 255u, 0u, 3u}, /* special case */
    {{'N','3','P'}, '\0', 255u, 0u, 3u}, /* Triple Play 2000 */
    {{'N','4','W'}, '\0', 255u, 0u, 3u}, /* 40 Winks (Aftermarket) */
    {{'N','6','4'}, '\0', 255u, 0u, 3u}, /* Kira to Kaiketsu! 64 Tanteidan */
    {{'N','7','I'}, '\0', 255u, 0u, 1u}, /* FIFA Soccer 64 [FIFA 64 (E)] */
    {{'N','8','I'}, '\0', 255u, 0u, 1u}, /* FIFA - Road to World Cup 98 [World Cup e no Michi (J)] */
    {{'N','8','M'}, '\0', 255u, 0u, 3u}, /* Madden Football 64 */
    {{'N','8','W'}, '\0', 255u, 0u, 1u}, /* World Cup '98 */
    {{'N','9','B'}, '\0', 255u, 0u, 3u}, /* NBA Live '99 */
    {{'N','9','C'}, '\0', 255u, 0u, 3u}, /* Nascar '99 */
    {{'N','9','F'}, '\0', 255u, 0u, 1u}, /* FIFA 99 */
    {{'N','9','H'}, '\0', 255u, 0u, 3u}, /* NHL '99 */
    {{'N','9','M'}, '\0', 255u, 0u, 3u}, /* Madden Football '99 */
    {{'N','A','2'}, '\0', 255u, 3u, 3u}, /* Virtual Pro Wrestling 2 */
    {{'N','A','B'}, '\0', 255u, 1u, 3u}, /* Air Boarder 64 */
    {{'N','A','C'}, '\0', 255u, 0u, 3u}, /* Army Men - Air Combat */
    {{'N','A','D'}, '\0', 255u, 1u, 0u}, /* Worms Armageddon (U) */
    {{'N','A','F'}, '\0', 255u, 5u, 9u}, /* Doubutsu no Mori */
    {{'N','A','G'}, '\0', 255u, 1u, 1u}, /* AeroGauge */
    {{'N','A','H'}, '\0', 255u, 0u, 3u}, /* Asteroids Hyper 64 */
    {{'N','A','I'}, '\0', 255u, 0u, 1u}, /* Midway's Greatest Arcade Hits Volume 1 */
    {{'N','A','L'}, '\0', 255u, 3u, 2u}, /* Super Smash Bros. [Nintendo All-Star! Dairantou Smash Brot */
    {{'N','A','M'}, '\0', 255u, 0u, 3u}, /* Army Men - Sarge's Heroes */
    {{'N','A','R'}, '\0', 255u, 0u, 3u}, /* Armorines - Project S.W.A.R.M. */
    {{'N','A','S'}, '\0', 255u, 0u, 3u}, /* All-Star Baseball 2001 */
    {{'N','A','Y'}, '\0', 255u, 0u, 1u}, /* Aidyn Chronicles - The First Mage */
    {{'N','B','2'}, '\0', 255u, 0u, 3u}, /* NBA In the Zone '99 [NBA Pro '99 (E)] */
    {{'N','B','3'}, '\0', 255u, 0u, 3u}, /* Bust-A-Move '99 [Bust-A-Move 3 DX (E)] */
    {{'N','B','4'}, '\0', 255u, 0u, 3u}, /* Bass Masters 2000 */
    {{'N','B','5'}, '\0', 255u, 3u, 2u}, /* Biohazard 2 (J) */
    {{'N','B','6'}, '\0', 255u, 1u, 5u}, /* Super B-Daman: Battle Phoenix 64 */
    {{'N','B','7'}, '\0', 255u, 2u, 2u}, /* Banjo-Tooie [Banjo to Kazooie no Daiboken 2 (J)] */
    {{'N','B','8'}, '\0', 255u, 0u, 3u}, /* Beetle Adventure Racing (J) */
    {{'N','B','9'}, '\0', 255u, 0u, 1u}, /* NBA Jam '99 */
    {{'N','B','A'}, '\0', 255u, 0u, 3u}, /* NBA In the Zone '98 [NBA Pro '98 (E)] */
    {{'N','B','C'}, '\0', 255u, 1u, 1u}, /* Blast Corps */
    {{'N','B','D'}, '\0', 255u, 1u, 2u}, /* Bomberman Hero [Mirian Ojo o Sukue! (J)] */
    {{'N','B','E'}, '\0', 255u, 0u, 3u}, /* All-Star Baseball 2000 */
    {{'N','B','F'}, '\0', 255u, 0u, 3u}, /* Bio F.R.E.A.K.S. */
    {{'N','B','H'}, '\0', 255u, 1u, 2u}, /* Body Harvest */
    {{'N','B','I'}, '\0', 255u, 0u, 3u}, /* NFL Blitz 2000 */
    {{'N','B','J'}, '\0', 255u, 0u, 1u}, /* Bakushou Jinsei 64 - Mezase! Resort Ou */
    {{'N','B','K'}, '\0', 255u, 1u, 2u}, /* Banjo-Kazooie [Banjo to Kazooie no Daiboken (J)] */
    {{'N','B','L'}, '\0', 255u, 0u, 3u}, /* Buck Bumble */
    {{'N','B','M'}, '\0', 255u, 1u, 1u}, /* Bomberman 64 [Baku Bomberman (J)] */
    {{'N','B','N'}, '\0', 255u, 1u, 1u}, /* Bakuretsu Muteki Bangaioh */
    {{'N','B','O'}, '\0', 255u, 0u, 1u}, /* Bottom of the 9th */
    {{'N','B','P'}, '\0', 255u, 0u, 3u}, /* Blues Brothers 2000 */
    {{'N','B','Q'}, '\0', 255u, 0u, 3u}, /* Battletanx - Global Assault */
    {{'N','B','R'}, '\0', 255u, 0u, 3u}, /* Milo's Astro Lanes */
    {{'N','B','S'}, '\0', 255u, 0u, 3u}, /* All-Star Baseball '99 */
    {{'N','B','U'}, '\0', 255u, 0u, 1u}, /* Bust-A-Move 2 - Arcade Edition */
    {{'N','B','V'}, '\0', 255u, 1u, 3u}, /* Bomberman 64: The Second Attack! [Baku Bomberman 2 (J)] */
    {{'N','B','W'}, '\0', 255u, 0u, 3u}, /* Super Bowling */
    {{'N','B','X'}, '\0', 255u, 0u, 3u}, /* Battletanx */
    {{'N','B','Y'}, '\0', 255u, 0u, 3u}, /* Bug's Life, A */
    {{'N','B','Z'}, '\0', 255u, 0u, 3u}, /* NFL Blitz */
    {{'N','C','B'}, '\0', 255u, 0u, 2u}, /* Charlie Blast's Territory */
    {{'N','C','C'}, '\0', 255u, 5u, 2u}, /* Command & Conquer */
    {{'N','C','D'}, '\0', 255u, 0u, 3u}, /* Carmageddon 64 */
    {{'N','C','E'}, '\0', 255u, 0u, 3u}, /* Nuclear Strike 64 */
    {{'N','C','G'}, '\0', 255u, 1u, 7u}, /* Choro Q 64 II - Hacha Mecha Grand Prix Race (J) */
    {{'N','C','H'}, '\0', 255u, 1u, 2u}, /* Chopper Attack */
    {{'N','C','K'}, '\0', 255u, 5u, 2u}, /* NBA Courtside 2 featuring Kobe Bryant */
    {{'N','C','L'}, '\0', 255u, 0u, 3u}, /* California Speed */
    {{'N','C','O'}, '\0', 255u, 0u, 3u}, /* Jeremy McGrath Supercross 2000 */
    {{'N','C','R'}, '\0', 255u, 1u, 1u}, /* Penny Racers [Choro Q 64 (J)] */
    {{'N','C','S'}, '\0', 255u, 0u, 3u}, /* S.C.A.R.S. */
    {{'N','C','T'}, '\0', 255u, 1u, 2u}, /* Chameleon Twist */
    {{'N','C','U'}, '\0', 255u, 1u, 1u}, /* Cruis'n USA */
    {{'N','C','V'}, '\0', 255u, 5u, 0u}, /* Cubivore [English translation/patch of Doubutsu Banchou (J */
    {{'N','C','W'}, '\0', 255u, 2u, 2u}, /* Cruis'n World */
    {{'N','C','X'}, '\0', 255u, 1u, 0u}, /* Custom Robo */
    {{'N','C','Z'}, '\0', 255u, 2u, 2u}, /* Custom Robo V2 */
    {{'N','D','2'}, '\0', 255u, 2u, 2u}, /* Doraemon 2: Nobita to Hikari no Shinden */
    {{'N','D','3'}, 'J', 255u, 2u, 2u}, /* special case */
    {{'N','D','3'}, '\0', 255u, 0u, 1u}, /* special case */
    {{'N','D','4'}, 'J', 255u, 2u, 2u}, /* special case */
    {{'N','D','4'}, '\0', 255u, 0u, 1u}, /* special case */
    {{'N','D','6'}, '\0', 255u, 2u, 2u}, /* Densha de Go! 64 */
    {{'N','D','A'}, '\0', 255u, 5u, 1u}, /* Derby Stallion 64 */
    {{'N','D','C'}, '\0', 255u, 0u, 3u}, /* SD Hiryuu no Ken Densetsu (J) */
    {{'N','D','E'}, '\0', 255u, 0u, 3u}, /* Destruction Derby 64 */
    {{'N','D','F'}, '\0', 255u, 0u, 2u}, /* Dance Dance Revolution - Disney Dancing Museum */
    {{'N','D','H'}, '\0', 255u, 0u, 1u}, /* Duel Heroes */
    {{'N','D','K'}, 'J', 255u, 1u, 0u},
    {{'N','D','M'}, '\0', 255u, 0u, 1u}, /* Doom 64 */
    {{'N','D','N'}, '\0', 255u, 0u, 3u}, /* Duke Nukem 64 */
    {{'N','D','O'}, '\0', 255u, 2u, 2u}, /* Donkey Kong 64 */
    {{'N','D','P'}, '\0', 255u, 5u, 0u}, /* Dinosaur Planet (Unlicensed) */
    {{'N','D','Q'}, '\0', 255u, 1u, 1u}, /* Disney's Donald Duck - Goin' Quackers [Quack Attack (E)] */
    {{'N','D','Q'}, '\0', 255u, 0u, 1u}, /* Disney's Donald Duck - Goin' Quackers [Quack Attack (E)] */
    {{'N','D','R'}, '\0', 255u, 1u, 0u}, /* Doraemon: Nobita to 3tsu no Seireiseki */
    {{'N','D','S'}, '\0', 255u, 0u, 1u}, /* J.League Dynamite Soccer 64 */
    {{'N','D','T'}, '\0', 255u, 0u, 3u}, /* South Park */
    {{'N','D','U'}, '\0', 255u, 1u, 2u}, /* Duck Dodgers starring Daffy Duck */
    {{'N','D','W'}, '\0', 255u, 0u, 3u}, /* Daikatana, John Romero's */
    {{'N','D','Y'}, '\0', 255u, 1u, 3u}, /* Diddy Kong Racing */
    {{'N','D','Z'}, '\0', 255u, 0u, 3u}, /* Duke Nukem - Zero Hour */
    {{'N','E','A'}, '\0', 255u, 1u, 0u}, /* PGA European Tour */
    {{'N','E','G'}, '\0', 255u, 0u, 3u}, /* Extreme-G */
    {{'N','E','P'}, '\0', 255u, 2u, 2u}, /* Star Wars Episode I: Racer */
    {{'N','E','R'}, '\0', 255u, 1u, 2u}, /* Aero Fighters Assault [Sonic Wings Assault (J)] */
    {{'N','E','T'}, '\0', 255u, 0u, 1u}, /* Quest 64 [Eltale Monsters (J) Holy Magic Century (E)] */
    {{'N','E','V'}, '\0', 255u, 2u, 2u}, /* Neon Genesis Evangelion */
    {{'N','F','2'}, '\0', 255u, 1u, 2u}, /* F-1 World Grand Prix II */
    {{'N','F','9'}, '\0', 255u, 0u, 1u}, /* Fox Sports College Hoops '99 */
    {{'N','F','B'}, '\0', 255u, 0u, 3u}, /* NFL Blitz 2001 */
    {{'N','F','D'}, '\0', 255u, 0u, 3u}, /* Flying Dragon */
    {{'N','F','F'}, '\0', 255u, 0u, 3u}, /* Fighting Force 64 */
    {{'N','F','G'}, '\0', 255u, 1u, 3u}, /* Fighter Destiny 2 */
    {{'N','F','H'}, '\0', 255u, 1u, 2u}, /* In-Fisherman Bass Hunter 64 */
    {{'N','F','L'}, '\0', 255u, 0u, 3u}, /* Madden Football 2001 */
    {{'N','F','O'}, '\0', 255u, 0u, 3u}, /* Forsaken 64 */
    {{'N','F','Q'}, '\0', 255u, 0u, 3u}, /* Razor Freestyle Scooter */
    {{'N','F','R'}, '\0', 255u, 0u, 3u}, /* F-1 Racing Championship */
    {{'N','F','S'}, '\0', 255u, 0u, 1u}, /* Famista 64 */
    {{'N','F','U'}, '\0', 255u, 2u, 2u}, /* Conker's Bad Fur Day */
    {{'N','F','W'}, '\0', 255u, 1u, 2u}, /* F-1 World Grand Prix */
    {{'N','F','X'}, '\0', 255u, 1u, 2u}, /* Star Fox 64 [Lylat Wars (E)] */
    {{'N','F','Y'}, '\0', 255u, 1u, 3u}, /* Kakutou Denshou: F-Cup Maniax */
    {{'N','F','Z'}, '\0', 255u, 3u, 2u}, /* F-Zero X (U + E) */
    {{'N','G','2'}, '\0', 255u, 0u, 3u}, /* Extreme-G XG2 */
    {{'N','G','5'}, '\0', 255u, 0u, 3u}, /* Ganbare Goemon - Neo Momoyama Bakufu no Odori [Mystical Ni */
    {{'N','G','6'}, '\0', 255u, 3u, 2u}, /* Ganmare Goemon: Dero Dero Douchuu Obake Tenkomori */
    {{'N','G','A'}, '\0', 255u, 0u, 3u}, /* Deadly Arts [G.A.S.P!! Fighter's NEXTream (E + J)] */
    {{'N','G','B'}, '\0', 255u, 0u, 3u}, /* Top Gear Hyper Bike */
    {{'N','G','C'}, '\0', 255u, 2u, 3u}, /* GT 64: Championship Edition */
    {{'N','G','D'}, '\0', 255u, 0u, 3u}, /* Gauntlet Legends (J) */
    {{'N','G','E'}, '\0', 255u, 1u, 2u}, /* GoldenEye 007 */
    {{'N','G','L'}, '\0', 255u, 1u, 3u}, /* Getter Love!! */
    {{'N','G','M'}, '\0', 255u, 0u, 3u}, /* Goemon's Great Adventure [Mystical Ninja 2 Starring Goemon */
    {{'N','G','N'}, '\0', 255u, 0u, 1u}, /* Golden Nugget 64 */
    {{'N','G','P'}, '\0', 255u, 3u, 1u}, /* Goemon: Mononoke Sugoroku */
    {{'N','G','R'}, '\0', 255u, 0u, 3u}, /* Top Gear Rally (U) */
    {{'N','G','S'}, '\0', 255u, 0u, 1u}, /* Jikkyou G1 Stable */
    {{'N','G','T'}, '\0', 255u, 2u, 3u}, /* City Tour GrandPrix - Zen Nihon GT Senshuken */
    {{'N','G','U'}, '\0', 255u, 1u, 2u}, /* Tsumi to Batsu: Hoshi no Keishousha (Sin and Punishment) */
    {{'N','G','V'}, '\0', 255u, 1u, 0u}, /* Glover */
    {{'N','G','X'}, '\0', 255u, 0u, 3u}, /* Gauntlet Legends */
    {{'N','H','5'}, '\0', 255u, 0u, 1u}, /* Nagano Winter Olympics '98 [Hyper Olympics in Nagano (J)] */
    {{'N','H','9'}, '\0', 255u, 0u, 3u}, /* NHL Breakaway '99 */
    {{'N','H','A'}, '\0', 255u, 1u, 1u}, /* Bomberman 64: Arcade Edition (J) */
    {{'N','H','C'}, '\0', 255u, 0u, 3u}, /* Hercules - The Legendary Journeys */
    {{'N','H','F'}, '\0', 255u, 1u, 0u}, /* 64 Hanafuda: Tenshi no Yakusoku */
    {{'N','H','G'}, '\0', 255u, 0u, 1u}, /* F-1 Pole Position 64 */
    {{'N','H','G'}, '\0', 255u, 0u, 1u}, /* Human Grand Prix - New Generation */
    {{'N','H','K'}, '\0', 255u, 0u, 3u}, /* Hiryuu no Ken Twin */
    {{'N','H','L'}, '\0', 255u, 0u, 3u}, /* NHL Breakaway '98 */
    {{'N','H','M'}, '\0', 255u, 0u, 3u}, /* Mia Hamm Soccer 64 */
    {{'N','H','N'}, '\0', 255u, 0u, 1u}, /* Olympic Hockey Nagano '98 */
    {{'N','H','O'}, '\0', 255u, 0u, 3u}, /* NHL Blades of Steel '99 [NHL Pro '99 (E)] */
    {{'N','H','P'}, '\0', 255u, 1u, 0u}, /* Heiwa Pachinko World 64 */
    {{'N','H','S'}, '\0', 255u, 0u, 1u}, /* Hamster Monogatari 64 */
    {{'N','H','T'}, '\0', 255u, 0u, 3u}, /* Hydro Thunder */
    {{'N','H','V'}, '\0', 255u, 0u, 3u}, /* Hybrid Heaven (U + E) */
    {{'N','H','W'}, '\0', 255u, 0u, 3u}, /* Hot Wheels Turbo Racing */
    {{'N','H','X'}, '\0', 255u, 0u, 1u}, /* Hexen */
    {{'N','H','Y'}, '\0', 255u, 3u, 3u}, /* Hybrid Heaven (J) */
    {{'N','I','B'}, '\0', 255u, 3u, 2u}, /* Itoi Shigesato no Bass Tsuri No. 1 Kettei Ban! */
    {{'N','I','C'}, '\0', 255u, 1u, 2u}, /* Indy Racing 2000 */
    {{'N','I','J'}, '\0', 255u, 1u, 2u}, /* Indiana Jones and the Infernal Machine */
    {{'N','I','M'}, '\0', 255u, 2u, 0u}, /* Ide Yosuke no Mahjong Juku */
    {{'N','I','R'}, '\0', 255u, 1u, 2u}, /* Utchan Nanchan no Hono no Challenger: Denryuu Ira Ira Bou */
    {{'N','I','S'}, '\0', 255u, 0u, 3u}, /* International Superstar Soccer 2000 */
    {{'N','I','V'}, '\0', 255u, 0u, 3u}, /* Space Invaders */
    {{'N','J','2'}, '\0', 255u, 0u, 1u}, /* Wonder Project J2 - Koruro no Mori no Jozet (J) */
    {{'N','J','3'}, '\0', 255u, 0u, 1u}, /* Jikkyou World Soccer 3 */
    {{'N','J','5'}, '\0', 255u, 3u, 1u}, /* Jikkyou Powerful Pro Yakyuu 5 */
    {{'N','J','A'}, '\0', 255u, 0u, 3u}, /* NBA Jam 2000 */
    {{'N','J','E'}, '\0', 255u, 0u, 1u}, /* J.League Eleven Beat 1997 */
    {{'N','J','F'}, '\0', 255u, 5u, 2u}, /* Jet Force Gemini [Star Twins (J)] */
    {{'N','J','G'}, '\0', 255u, 3u, 2u}, /* Jinsei Game 64 */
    {{'N','J','K'}, '\0', 255u, 1u, 2u}, /* Viewpoint 2064 (Master) */
    {{'N','J','L'}, '\0', 255u, 0u, 1u}, /* J.League Live 64 */
    {{'N','J','M'}, '\0', 255u, 1u, 0u}, /* Earthworm Jim 3D */
    {{'N','J','P'}, '\0', 255u, 0u, 1u}, /* International Superstar Soccer 64 [Jikkyo J-League Perfect */
    {{'N','J','Q'}, '\0', 255u, 0u, 2u}, /* Batman Beyond - Return of the Joker [Batman of the Future  */
    {{'N','K','2'}, '\0', 255u, 1u, 2u}, /* Snowboard Kids 2 [Chou Snobow Kids (J)] */
    {{'N','K','4'}, 'J', 1u, 3u, 2u}, /* special case */
    {{'N','K','4'}, '\0', 255u, 2u, 2u}, /* special case */
    {{'N','K','A'}, '\0', 255u, 1u, 3u}, /* Fighters Destiny [Fighting Cup (J)] */
    {{'N','K','E'}, '\0', 255u, 0u, 2u}, /* Knife Edge - Nose Gunner */
    {{'N','K','G'}, '\0', 255u, 3u, 3u}, /* Major League Baseball featuring Ken Griffey Jr. */
    {{'N','K','I'}, '\0', 255u, 1u, 1u}, /* Killer Instinct Gold */
    {{'N','K','J'}, '\0', 255u, 5u, 2u}, /* Ken Griffey Jr.'s Slugfest */
    {{'N','K','K'}, '\0', 255u, 0u, 3u}, /* Knockout Kings 2000 */
    {{'N','K','M'}, '\0', 255u, 0u, 1u}, /* Pro Mahjong Kiwame 64 (J) */
    {{'N','K','R'}, '\0', 255u, 0u, 1u}, /* Rakuga Kids (E) */
    {{'N','K','T'}, '\0', 255u, 1u, 1u}, /* Mario Kart 64 */
    {{'N','L','2'}, '\0', 255u, 0u, 3u}, /* Top Gear Rally 2 */
    {{'N','L','B'}, '\0', 255u, 1u, 2u}, /* Mario Party (PAL) */
    {{'N','L','C'}, '\0', 255u, 0u, 3u}, /* Automobili Lamborghini [Super Speed Race 64 (J)] */
    {{'N','L','G'}, '\0', 255u, 0u, 3u}, /* LEGO Racers */
    {{'N','L','L'}, '\0', 255u, 1u, 2u}, /* Last Legion UX */
    {{'N','L','R'}, '\0', 255u, 1u, 2u}, /* Lode Runner 3-D */
    {{'N','M','3'}, '\0', 255u, 0u, 2u}, /* Monster Truck Madness 64 */
    {{'N','M','4'}, '\0', 255u, 0u, 3u}, /* Mortal Kombat 4 */
    {{'N','M','6'}, '\0', 255u, 5u, 2u}, /* Mega Man 64 */
    {{'N','M','8'}, '\0', 255u, 2u, 6u}, /* Mario Tennis */
    {{'N','M','9'}, '\0', 255u, 0u, 1u}, /* Harukanaru Augusta Masters 98 */
    {{'N','M','A'}, '\0', 255u, 0u, 1u}, /* Jangou Simulation Mahjong Do 64 */
    {{'N','M','B'}, '\0', 255u, 0u, 3u}, /* Mike Piazza's Strike Zone */
    {{'N','M','D'}, '\0', 255u, 0u, 3u}, /* Madden Football 2000 */
    {{'N','M','F'}, '\0', 255u, 3u, 6u}, /* Mario Golf 64 */
    {{'N','M','G'}, '\0', 255u, 1u, 3u}, /* Monaco Grand Prix [Racing Simulation 2 (G)] */
    {{'N','M','I'}, '\0', 255u, 1u, 2u}, /* Mission: Impossible */
    {{'N','M','J'}, '\0', 255u, 0u, 1u}, /* Mahjong 64 */
    {{'N','M','L'}, '\0', 255u, 1u, 6u}, /* Mickey's Speedway USA [Mickey no Racing Challenge USA (J)] */
    {{'N','M','M'}, '\0', 255u, 0u, 1u}, /* Mahjong Master */
    {{'N','M','O'}, '\0', 255u, 1u, 0u}, /* Monopoly */
    {{'N','M','Q'}, '\0', 255u, 5u, 2u}, /* Paper Mario */
    {{'N','M','R'}, '\0', 255u, 1u, 3u}, /* Multi-Racing Championship */
    {{'N','M','S'}, '\0', 255u, 1u, 1u}, /* Morita Shougi 64 */
    {{'N','M','T'}, '\0', 255u, 0u, 2u}, /* Magical Tetris Challenge */
    {{'N','M','U'}, '\0', 255u, 1u, 3u}, /* Big Mountain 2000 */
    {{'N','M','V'}, '\0', 255u, 2u, 2u}, /* Mario Party 3 */
    {{'N','M','W'}, '\0', 255u, 1u, 2u}, /* Mario Party 2 */
    {{'N','M','X'}, '\0', 255u, 2u, 3u}, /* Excitebike 64 */
    {{'N','M','Y'}, '\0', 255u, 0u, 3u}, /* Mortal Kombat Mythologies - Sub-Zero */
    {{'N','M','Z'}, '\0', 255u, 1u, 0u}, /* Zool - Majou Tsukai Densetsu (J) */
    {{'N','N','2'}, '\0', 255u, 0u, 3u}, /* Nascar 2000 */
    {{'N','N','6'}, '\0', 255u, 1u, 0u}, /* Dr. Mario 64 */
    {{'N','N','A'}, '\0', 255u, 1u, 2u}, /* Star Wars Episode I: Battle for Naboo */
    {{'N','N','B'}, '\0', 255u, 2u, 3u}, /* Kobe Bryant in NBA Courtside */
    {{'N','N','C'}, '\0', 255u, 0u, 3u}, /* Nightmare Creatures */
    {{'N','N','L'}, '\0', 255u, 0u, 3u}, /* NBA Live 2000 */
    {{'N','N','M'}, '\0', 255u, 0u, 1u}, /* Namco Museum 64 */
    {{'N','N','R'}, '\0', 255u, 0u, 1u}, /* Pro Mahjong Tsuwamono 64 - Jansou Battle ni Chousen (J) */
    {{'N','N','S'}, '\0', 255u, 0u, 3u}, /* Beetle Adventure Racing */
    {{'N','O','7'}, '\0', 255u, 0u, 3u}, /* The World Is Not Enough */
    {{'N','O','B'}, '\0', 255u, 3u, 0u}, /* Ogre Battle 64: Person of Lordly Caliber */
    {{'N','O','F'}, '\0', 255u, 0u, 3u}, /* Offroad Challenge */
    {{'N','O','H'}, '\0', 255u, 0u, 6u}, /* Transformers Beast Wars - Transmetals */
    {{'N','O','M'}, '\0', 255u, 0u, 1u}, /* Onegai Monsters */
    {{'N','O','S'}, '\0', 255u, 1u, 3u}, /* 64 Oozumou */
    {{'N','O','W'}, '\0', 255u, 0u, 1u}, /* Brunswick Circuit Pro Bowling */
    {{'N','P','2'}, '\0', 255u, 1u, 3u}, /* Chou Kuukan Night Pro Yakyuu King 2 (J) */
    {{'N','P','3'}, '\0', 255u, 5u, 4u}, /* Pokemon Stadium 2 [Pocket Monsters Stadium - Kin Gin (J)] */
    {{'N','P','4'}, '\0', 255u, 3u, 1u}, /* Jikkyou Powerful Pro Yakyuu 4 */
    {{'N','P','6'}, '\0', 255u, 3u, 5u}, /* Jikkyou Powerful Pro Yakyuu 6 */
    {{'N','P','9'}, '\0', 255u, 0u, 3u}, /* Ms. Pac-Man - Maze Madness */
    {{'N','P','A'}, '\0', 255u, 3u, 5u}, /* Jikkyou Powerful Pro Yakyuu 2000 */
    {{'N','P','B'}, '\0', 255u, 0u, 3u}, /* Puzzle Bobble 64 (J) */
    {{'N','P','C'}, '\0', 255u, 0u, 1u}, /* Pachinko 365 Nichi (J) */
    {{'N','P','D'}, '\0', 255u, 2u, 7u}, /* Perfect Dark */
    {{'N','P','E'}, '\0', 255u, 3u, 1u}, /* Jikkyou Powerful Pro Yakyuu Basic Ban 2001 */
    {{'N','P','F'}, '\0', 255u, 5u, 0u}, /* Pokemon Snap [Pocket Monsters Snap (J)] */
    {{'N','P','G'}, '\0', 255u, 1u, 2u}, /* Hey You, Pikachu! [Pikachu Genki Dechu (J)] */
    {{'N','P','K'}, '\0', 255u, 0u, 1u}, /* Chou Kuukan Night Pro Yakyuu King (J) */
    {{'N','P','L'}, '\0', 255u, 0u, 1u}, /* Power League 64 (J) */
    {{'N','P','M'}, '\0', 255u, 3u, 1u}, /* Premier Manager 64 */
    {{'N','P','N'}, '\0', 255u, 5u, 0u}, /* Pokemon Puzzle League */
    {{'N','P','O'}, '\0', 255u, 5u, 4u}, /* Pokemon Stadium */
    {{'N','P','P'}, '\0', 255u, 2u, 1u}, /* Parlor! Pro 64: Pachinko Jikki Simulation Game */
    {{'N','P','R'}, '\0', 255u, 0u, 3u}, /* South Park Rally */
    {{'N','P','S'}, '\0', 255u, 3u, 3u}, /* Jikkyou J.League 1999: Perfect Striker 2 */
    {{'N','P','T'}, '\0', 255u, 1u, 6u}, /* Puyo Puyon Party */
    {{'N','P','U'}, '\0', 255u, 0u, 1u}, /* Power Rangers - Lightspeed Rescue */
    {{'N','P','W'}, '\0', 255u, 1u, 0u}, /* Pilotwings 64 */
    {{'N','P','X'}, '\0', 255u, 0u, 3u}, /* Polaris SnoCross */
    {{'N','P','Y'}, '\0', 255u, 1u, 2u}, /* Puyo Puyo Sun 64 */
    {{'N','P','Z'}, '\0', 255u, 0u, 3u}, /* Susume! Taisen Puzzle Dama Toukon! Marumata Chou (J) */
    {{'N','Q','2'}, '\0', 255u, 0u, 3u}, /* Quake 2 */
    {{'N','Q','8'}, '\0', 255u, 0u, 3u}, /* NFL Quarterback Club '98 */
    {{'N','Q','9'}, '\0', 255u, 0u, 3u}, /* NFL Quarterback Club '99 */
    {{'N','Q','B'}, '\0', 255u, 0u, 3u}, /* NFL Quarterback Club 2000 */
    {{'N','Q','C'}, '\0', 255u, 0u, 3u}, /* NFL Quarterback Club 2001 */
    {{'N','Q','K'}, '\0', 255u, 0u, 3u}, /* Quake 64 */
    {{'N','R','2'}, '\0', 255u, 0u, 3u}, /* Rush 2 - Extreme Racing USA */
    {{'N','R','3'}, '\0', 255u, 0u, 3u}, /* Stunt Racer 64 */
    {{'N','R','6'}, '\0', 255u, 0u, 3u}, /* Tom Clancy's Rainbow Six */
    {{'N','R','7'}, '\0', 255u, 2u, 4u}, /* Robot Poncots 64: 7tsu no Umi no Caramel */
    {{'N','R','A'}, '\0', 255u, 1u, 3u}, /* Rally '99 (J) */
    {{'N','R','C'}, '\0', 255u, 1u, 2u}, /* Top Gear Overdrive */
    {{'N','R','D'}, '\0', 255u, 0u, 3u}, /* Ready 2 Rumble Boxing */
    {{'N','R','E'}, '\0', 255u, 3u, 2u}, /* Resident Evil 2 */
    {{'N','R','G'}, '\0', 255u, 0u, 2u}, /* Rugrats - Scavenger Hunt [Treasure Hunt (E)] */
    {{'N','R','H'}, '\0', 255u, 5u, 2u}, /* Rockman Dash - Hagane no Boukenshin (J) */
    {{'N','R','I'}, '\0', 255u, 3u, 1u}, /* New Tetris, The */
    {{'N','R','K'}, '\0', 255u, 0u, 1u}, /* Rugrats in Paris - The Movie */
    {{'N','R','O'}, '\0', 255u, 0u, 3u}, /* Road Rash 64 */
    {{'N','R','P'}, '\0', 255u, 0u, 3u}, /* Rampage - World Tour */
    {{'N','R','R'}, '\0', 255u, 0u, 3u}, /* Roadster's Trophy */
    {{'N','R','S'}, '\0', 255u, 1u, 2u}, /* Star Wars: Rogue Squadron [Shutsugeki! Rogue Chuutai (J)] */
    {{'N','R','T'}, '\0', 255u, 0u, 1u}, /* Rat Attack */
    {{'N','R','T'}, '\0', 255u, 0u, 1u}, /* Robotron 64 */
    {{'N','R','U'}, '\0', 255u, 0u, 3u}, /* San Francisco Rush 2049 */
    {{'N','R','V'}, '\0', 255u, 0u, 3u}, /* Re-Volt */
    {{'N','R','W'}, '\0', 255u, 0u, 3u}, /* Turok: Rage Wars */
    {{'N','R','Z'}, '\0', 255u, 2u, 2u}, /* Ridge Racer 64 */
    {{'N','S','2'}, '\0', 255u, 0u, 1u}, /* Simcity 2000 */
    {{'N','S','3'}, '\0', 255u, 1u, 1u}, /* AI Shougi 3 */
    {{'N','S','4'}, '\0', 255u, 3u, 5u}, /* Super Robot Taisen 64 */
    {{'N','S','6'}, '\0', 255u, 1u, 2u}, /* Star Soldier: Vanishing Earth */
    {{'N','S','A'}, '\0', 255u, 1u, 2u}, /* Sonic Wings Assault (J) */
    {{'N','S','B'}, '\0', 255u, 0u, 3u}, /* Twisted Edge - Extreme Snowboarding [King Hill 64 - Extrem */
    {{'N','S','C'}, '\0', 255u, 1u, 0u}, /* Starshot: Space Circus Fever */
    {{'N','S','D'}, '\0', 255u, 0u, 3u}, /* Shadow Man */
    {{'N','S','F'}, '\0', 255u, 0u, 3u}, /* San Francisco Rush - Extreme Racing */
    {{'N','S','G'}, '\0', 255u, 0u, 1u}, /* Shadowgate 64 - Trials Of The Four Towers */
    {{'N','S','H'}, '\0', 255u, 0u, 1u}, /* Saikyou Habu Shougi (J) */
    {{'N','S','I'}, '\0', 255u, 3u, 1u}, /* Fushigi no Dungeon: Fuurai no Shiren 2 */
    {{'N','S','K'}, '\0', 255u, 0u, 3u}, /* Snowboard Kids [Snobow Kids (J)] */
    {{'N','S','L'}, '\0', 255u, 0u, 3u}, /* Spider-Man */
    {{'N','S','M'}, '\0', 255u, 1u, 0u}, /* special case */
    {{'N','S','N'}, '\0', 255u, 1u, 3u}, /* Snow Speeder (J) */
    {{'N','S','O'}, '\0', 255u, 0u, 1u}, /* NBA Showtime - NBA on NBC */
    {{'N','S','P'}, '\0', 255u, 0u, 3u}, /* Superman */
    {{'N','S','Q'}, '\0', 255u, 5u, 2u}, /* StarCraft 64 */
    {{'N','S','S'}, '\0', 255u, 1u, 2u}, /* Super Robot Spirits */
    {{'N','S','T'}, '\0', 255u, 0u, 1u}, /* Eikou no Saint Andrews */
    {{'N','S','U'}, '\0', 255u, 1u, 2u}, /* Rocket: Robot on Wheels */
    {{'N','S','V'}, '\0', 255u, 1u, 2u}, /* Space Station Silicon Valley */
    {{'N','S','W'}, '\0', 255u, 1u, 0u}, /* Star Wars: Shadows of the Empire [Teikoku no Kage (J)] */
    {{'N','S','X'}, '\0', 255u, 0u, 3u}, /* Supercross 2000 */
    {{'N','S','Y'}, '\0', 255u, 0u, 1u}, /* Scooby-Doo! - Classic Creep Capers */
    {{'N','S','Z'}, '\0', 255u, 0u, 3u}, /* NFL Blitz - Special Edition */
    {{'N','T','2'}, '\0', 255u, 0u, 3u}, /* Turok 2 - Seeds of Evil [Violence Killer - Turok New Gener */
    {{'N','T','3'}, '\0', 255u, 3u, 1u}, /* Shin Nihon Pro Wrestling - Toukon Road 2 - The Next Genera */
    {{'N','T','3'}, '\0', 255u, 0u, 3u}, /* Tony Hawk's Pro Skater 3 */
    {{'N','T','4'}, '\0', 255u, 0u, 3u}, /* CyberTiger */
    {{'N','T','6'}, '\0', 255u, 1u, 0u}, /* Tetris 64 */
    {{'N','T','9'}, '\0', 255u, 5u, 0u}, /* Tigger's Honey Hunt */
    {{'N','T','A'}, '\0', 255u, 0u, 3u}, /* Disney's Tarzan */
    {{'N','T','B'}, '\0', 255u, 1u, 2u}, /* Transformers: Beast Wars Metals 64 (J) */
    {{'N','T','C'}, '\0', 255u, 1u, 2u}, /* 64 Trump Collection */
    {{'N','T','D'}, '\0', 255u, 0u, 3u}, /* O.D.T. (Unreleased) */
    {{'N','T','E'}, '\0', 255u, 3u, 2u}, /* 1080 Snowboarding */
    {{'N','T','F'}, '\0', 255u, 0u, 3u}, /* Tony Hawk's Pro Skater */
    {{'N','T','H'}, '\0', 255u, 0u, 3u}, /* Toy Story 2 - Buzz Lightyear to the Rescue! */
    {{'N','T','I'}, '\0', 255u, 0u, 3u}, /* WWF: Attitude */
    {{'N','T','J'}, '\0', 255u, 1u, 2u}, /* Tom & Jerry in Fists of Fury */
    {{'N','T','K'}, '\0', 255u, 0u, 3u}, /* Turok 3 - Shadow of Oblivion */
    {{'N','T','M'}, '\0', 255u, 1u, 0u}, /* Mischief Makers [Yuke Yuke!! Trouble Makers (J)] */
    {{'N','T','N'}, '\0', 255u, 1u, 0u}, /* All Star Tennis '99 */
    {{'N','T','O'}, '\0', 255u, 0u, 1u}, /* Shin Nihon Pro Wrestling - Toukon Road - Brave Spirits (J) */
    {{'N','T','P'}, '\0', 255u, 1u, 0u}, /* Tetrisphere */
    {{'N','T','Q'}, '\0', 255u, 0u, 3u}, /* Tony Hawk's Pro Skater 2 */
    {{'N','T','R'}, '\0', 255u, 1u, 3u}, /* Top Gear Rally (J + E) */
    {{'N','T','S'}, '\0', 255u, 0u, 1u}, /* Centre Court Tennis [Let's Smash (J)] */
    {{'N','T','T'}, '\0', 255u, 0u, 1u}, /* Tonic Trouble */
    {{'N','T','U'}, '\0', 255u, 0u, 1u}, /* Turok: Dinosaur Hunter [Turok: Jikuu Senshi (J)] */
    {{'N','T','W'}, '\0', 255u, 1u, 1u}, /* 64 de Hakken!! Tamagotchi */
    {{'N','T','X'}, '\0', 255u, 1u, 2u}, /* Taz Express */
    {{'N','U','B'}, '\0', 255u, 2u, 5u}, /* PD Ultraman Battle Collection 64 */
    {{'N','U','M'}, '\0', 255u, 3u, 6u}, /* Nushi Zuri 64: Shiokaze ni Notte */
    {{'N','U','T'}, '\0', 255u, 3u, 7u}, /* Nushi Zuri 64 */
    {{'N','V','2'}, '\0', 255u, 0u, 3u}, /* Chameleon Twist 2 (J) */
    {{'N','V','3'}, '\0', 255u, 0u, 3u}, /* Micro Machines 64 Turbo */
    {{'N','V','8'}, '\0', 255u, 0u, 3u}, /* Vigilante 8 */
    {{'N','V','B'}, '\0', 255u, 3u, 2u}, /* Bass Rush - ECOGEAR PowerWorm Championship (J) */
    {{'N','V','C'}, '\0', 255u, 0u, 1u}, /* Virtual Chess 64 */
    {{'N','V','G'}, '\0', 255u, 0u, 3u}, /* Vigilante 8 - Second Offense */
    {{'N','V','L'}, '\0', 255u, 1u, 2u}, /* V-Rally Edition '99 */
    {{'N','V','P'}, '\0', 255u, 3u, 3u}, /* Virtual Pro Wrestling 64 */
    {{'N','V','R'}, '\0', 255u, 0u, 1u}, /* Virtual Pool 64 */
    {{'N','V','Y'}, '\0', 255u, 1u, 2u}, /* V-Rally Edition '99 (J) */
    {{'N','W','2'}, '\0', 255u, 3u, 2u}, /* WCW-nWo Revenge */
    {{'N','W','3'}, '\0', 255u, 0u, 3u}, /* WCW: Nitro */
    {{'N','W','4'}, '\0', 255u, 5u, 3u}, /* WWF No Mercy */
    {{'N','W','8'}, '\0', 255u, 0u, 1u}, /* Wayne Gretzky's 3D Hockey '98 */
    {{'N','W','B'}, '\0', 255u, 0u, 3u}, /* Iggy's Reckin' Balls [Iggy-kun no Bura Bura Poyon (J)] */
    {{'N','W','C'}, '\0', 255u, 1u, 2u}, /* Wild Choppers */
    {{'N','W','D'}, '\0', 255u, 0u, 3u}, /* Winback - Covert Operations */
    {{'N','W','F'}, '\0', 255u, 0u, 2u}, /* Wheel of Fortune */
    {{'N','W','G'}, '\0', 255u, 0u, 1u}, /* Wayne Gretzky's 3D Hockey */
    {{'N','W','I'}, '\0', 255u, 0u, 3u}, /* ECW Hardcore Revolution */
    {{'N','W','K'}, '\0', 255u, 0u, 3u}, /* Michael Owens WLS 2000 [World League Soccer 2000 (E) / Tel */
    {{'N','W','L'}, '\0', 255u, 3u, 2u}, /* Waialae Country Club: True Golf Classics */
    {{'N','W','M'}, '\0', 255u, 0u, 3u}, /* WCW: Mayhem */
    {{'N','W','N'}, '\0', 255u, 0u, 3u}, /* WCW vs. nWo - World Tour */
    {{'N','W','O'}, '\0', 255u, 0u, 3u}, /* World Driver Championship */
    {{'N','W','P'}, '\0', 255u, 0u, 3u}, /* Wipeout 64 */
    {{'N','W','Q'}, '\0', 255u, 1u, 3u}, /* Rally Challenge 2000 */
    {{'N','W','R'}, '\0', 255u, 1u, 1u}, /* special case */
    {{'N','W','S'}, '\0', 255u, 0u, 1u}, /* International Superstar Soccer '98 [Jikkyo World Soccer -  */
    {{'N','W','T'}, 'J', 255u, 1u, 0u}, /* special case */
    {{'N','W','T'}, '\0', 255u, 0u, 1u}, /* special case */
    {{'N','W','U'}, '\0', 255u, 1u, 0u}, /* Worms Armageddon (E) */
    {{'N','W','V'}, '\0', 255u, 0u, 3u}, /* WCW: Backstage Assault */
    {{'N','W','W'}, '\0', 255u, 0u, 3u}, /* WWF: War Zone */
    {{'N','W','X'}, '\0', 255u, 3u, 3u}, /* WWF WrestleMania 2000 */
    {{'N','W','Z'}, '\0', 255u, 0u, 3u}, /* NBA In the Zone 2000 */
    {{'N','X','2'}, '\0', 255u, 0u, 1u}, /* Gex 64 - Enter the Gecko */
    {{'N','X','3'}, '\0', 255u, 0u, 3u}, /* Gex 3 - Deep Cover Gecko */
    {{'N','X','C'}, '\0', 255u, 0u, 3u}, /* Xeno Crisis (Aftermarket) */
    {{'N','X','F'}, '\0', 255u, 0u, 3u}, /* Xena Warrior Princess - The Talisman of Fate */
    {{'N','X','G'}, '\0', 255u, 0u, 1u}, /* NBA Hangtime */
    {{'N','X','O'}, '\0', 255u, 1u, 2u}, /* Cruis'n Exotica */
    {{'N','Y','2'}, '\0', 255u, 0u, 1u}, /* Rayman 2 - The Great Escape */
    {{'N','Y','K'}, '\0', 255u, 1u, 2u}, /* Yakouchuu II: Satsujin Kouro */
    {{'N','Y','P'}, '\0', 255u, 0u, 3u}, /* Paperboy */
    {{'N','Y','S'}, '\0', 255u, 2u, 2u}, /* Yoshi's Story */
    {{'N','Y','W'}, '\0', 255u, 3u, 0u}, /* Harvest Moon 64 */
    {{'N','Y','W'}, '\0', 255u, 0u, 1u}, /* Bokujou Monogatari 2 */
    {{'N','Z','L'}, '\0', 255u, 3u, 2u}, /* Legend of Zelda: Ocarina of Time (E) */
    {{'N','Z','O'}, '\0', 255u, 0u, 3u}, /* Battlezone - Rise of the Black Dogs */
    {{'N','Z','S'}, '\0', 255u, 5u, 2u}, /* Legend of Zelda: Majora's Mask [Zelda no Densetsu - Mujura */
};

const sm_rom_db_entry_t *sm_rom_db_lookup(const uint8_t *header, size_t length) {
    if (!header || length < 0x40u) return NULL;
    {
        const char a = (char)header[0x3Bu], b = (char)header[0x3Cu];
        const char c = (char)header[0x3Du], region = (char)header[0x3Eu];
        const uint8_t revision = header[0x3Fu];
        /* Entries are emitted most specific first, so the first hit wins. */
        for (size_t i = 0; i < SM_ROM_DB_COUNT; i++) {
            const sm_rom_db_entry_t *e = &ROM_DB[i];
            if (e->id[0] != a || e->id[1] != b || e->id[2] != c) continue;
            if (e->region != '\0' && e->region != region) continue;
            if (e->rev_max != 255u && revision > e->rev_max) continue;
            return e;
        }
        return NULL;
    }
}
