/* SPDX-License-Identifier: ISC
 *
 * Derived from the Nintendo 64 save-type database in the ares emulator
 * (mia/medium/nintendo-64.cpp). ares is ISC licensed and its notice is
 * retained here as that licence requires:
 *
 *   Copyright (c) 2004-2025 ares team, Near et al
 *
 *   Permission to use, copy, modify, and/or distribute this software for any
 *   purpose with or without fee is hereby granted, provided that the above
 *   copyright notice and this permission notice appear in all copies.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *   WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *   ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *   WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *   ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *   OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#ifndef SLEEKMENU_ROM_DB_H
#define SLEEKMENU_ROM_DB_H

/* GENERATED by tools/build_rom_db.py -- do not edit by hand.
   Source: https://raw.githubusercontent.com/ares-emulator/ares/master/mia/medium/nintendo-64.cpp
   ares is ISC licensed. Save-type ids are krikzz's REG_GAM_CFG values. */

#include <stddef.h>
#include <stdint.h>

#define SM_FEAT_CPAK 1u  /* Controller Pak */
#define SM_FEAT_RPAK 2u  /* Rumble Pak */
#define SM_FEAT_TPAK 4u  /* Transfer Pak */
#define SM_FEAT_RTC 8u   /* real time clock */

typedef struct {
    char id[3];      /* ROM header bytes 0x3B..0x3D */
    char region;     /* header 0x3E, or 0 when the entry is region agnostic */
    uint8_t rev_max; /* entry applies when header 0x3F <= this; 255 = any */
    uint8_t save;    /* sm_save_type_t value */
    uint8_t feat;    /* SM_FEAT_* bits */
} sm_rom_db_entry_t;

#define SM_ROM_DB_COUNT 412u

/* header must be at least 0x40 bytes. Returns NULL when the game is absent,
   which means "no save hardware" exactly as it does for the stock firmware. */
const sm_rom_db_entry_t *sm_rom_db_lookup(const uint8_t *header, size_t length);

#endif
